"use client";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Provider } from "react-redux";
import { store } from "../Redux/Store";
import "@/css/variables.css"; // Import your variables
import "@/css/globals.css"; // Import your global styles
import { ToastContainer } from "react-toastify";

import WholeAppWrapper from "./WholeAppWrapper";
import { AppContextProvider } from "@/Context/AppContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <AppContextProvider>
        {/* <Provider store={store}> */}
          <html lang="en">
            <body
              className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
              <WholeAppWrapper>{children}</WholeAppWrapper>
              <ToastContainer />
            </body>
          </html>
        {/* </Provider> */}
      </AppContextProvider>
    </>
  );
}
